#!/usr/bin/env python3
"""Build the Vol 1 Issue 1 import migration from docx-to-articles.py output.

Usage: python3 scripts/build-vol1-import-sql.py <articles.json> <out.sql>
Images are served from /articles/vol-1-issue-1/<name>.webp (public/).
"""
import json, math, re, sys

ISSUE_ID = "33333333-3333-3333-3333-333333330001"  # Vol 1, Issue 1 (live DB)
AFFILIATION = "ICAR–Central Arid Zone Research Institute, Regional Research Station, Jaisalmer, Rajasthan"
IMG = "/articles/vol-1-issue-1/"

# Order follows the manuscript. Existing slugs are kept so already-shared links keep working.
META = [
    ("intellectual-property-agriculture-western-rajasthan", "Intellectual Property in Agriculture in Western Rajasthan", "extension"),
    ("rural-knowledge-centers-jaisalmer", "Advantages of Rural Knowledge Centers (RKC) in Jaisalmer", "ict-in-agriculture"),
    ("village-knowledge-centers-arid-zone", "Role of Village Knowledge Centers (VKC) in the Development of Villages in the Arid Zone", "ict-in-agriculture"),
    ("precision-farming-western-rajasthan", "Precision Farming in Western Rajasthan", "agri-tech"),
    ("ict-tools-agriculture-development-thar-desert", "Importance of ICT for Agriculture Development in the Thar Desert", "ict-in-agriculture"),
    ("bridging-digital-divide-arid-western-rajasthan", "Bridging the Digital Divide in Arid Western Rajasthan", "ict-in-agriculture"),
    ("rural-technology-parks-arid-agriculture-western-rajasthan", "Importance of Technology Parks / Rural Tech Parks in Arid Agriculture of Western Rajasthan", "agri-tech"),
    ("atic-cazri-jodhpur-farmers-development", "Agriculture Technology Information Centre (ATIC) of CAZRI Jodhpur: Role in Farmers' Development", "extension"),
    ("e-governance-agriculture-western-rajasthan", "Importance of E-Governance in Agriculture for Increasing Production in Western Rajasthan", "ict-in-agriculture"),
    ("cyber-extension-value-addition-jaisalmer", "Role of Cyber Extension in Value Addition in Jaisalmer District of Western Rajasthan", "ict-in-agriculture"),
    ("dynamics-of-e-learning", "Dynamics of E-Learning in Hyper-Arid Jaisalmer", "ict-in-agriculture"),
    ("mis-for-managing-agriculture-in-thar-desert", "Importance of Management Information System (MIS) for Managing Agriculture in the Thar Desert", "information-systems"),
    ("conceptual-framework-information-kiosk-western-rajasthan", "Conceptual Framework of Information Kiosk in Western Rajasthan", "ict-in-agriculture"),
    ("mis-increasing-production-arid-western-rajasthan", "Importance of Management Information System (MIS) in Increasing Production in the Arid Region of Western Rajasthan", "information-systems"),
    ("akis-for-farmers-western-rajasthan", "Agriculture Knowledge Information System (AKIS) for Increasing Knowledge of Farmers in Western Rajasthan", "extension-akis"),
    ("contract-farming-jeera-isabgol-pomegranate-western-rajasthan", "Contract Farming for Remunerative Prices of Jeera, Isabgol and Pomegranate in Western Rajasthan", "contract-farming"),
    ("ict-for-agriculture-thar-desert", "Importance of ICT for Agriculture Development in the Thar Desert of Rajasthan", "ict-in-agriculture"),
    ("pmddky-importance-in-jaisalmer", "PMDDKY: Pradhan Mantri Dhan-Dhaanya Krishi Yojana – Importance in Jaisalmer", "extension"),
]


def authors(raw):
    s = " ".join(raw)
    s = re.split(r"(?i)\(?\s*(?:[\d¹²³⁴,\s]*)\s*scientists?\b", s)[0]
    s = re.sub(r"[¹²³⁴⁰]|\d", "", s)
    s = re.sub(r"([a-z])\.?\s+(?=[A-Z]\.\s?[A-Z])", r"\1, ", s)  # "Kumar R.S." -> "Kumar, R.S."
    names = [n.strip(" .,") for n in re.split(r",|\s(?=[A-Z]\.\s?[A-Z][a-z])", s) if n.strip(" .,")]
    out = []
    for n in names:
        n = re.sub(r"\.(?=[A-Za-z])", ". ", n)          # "D.Kumar" -> "D. Kumar"
        n = re.sub(r"\s+", " ", n).strip(" .")
        n = re.sub(r"^([A-Z][a-z]+)\.? ?K$", r"\1 K.", n)  # "Saren K" -> "Saren K."
        out.append(n)
    return ", ".join(out)


def q(s):
    assert "$c$" not in s
    return f"$c${s}$c$"


arts = json.load(open(sys.argv[1]))
assert len(arts) == len(META), (len(arts), len(META))
rows = []
for a, (slug, title, cat) in zip(arts, META):
    content = a["html"].replace('src="__IMG__', f'src="{IMG}').replace('.jpeg"', '.webp"')
    content = content.replace('alt=""', f'alt="{title.replace(chr(34), "")}"', 1)
    cover = IMG + a["images"][0].replace(".jpeg", ".webp") if a["images"] else None
    abstract = a["abstract"]
    if len(abstract) > 400:
        abstract = abstract[:400].rsplit(" ", 1)[0] + "…"
    rows.append(f"""  ({q(slug)}, {q(title)}, {q(authors(a['authors_raw']))}, {q(abstract)}, {q(content)},
   {q(cover) if cover else 'NULL'}, {max(1, math.ceil(a['words'] / 200))}, '{cat}')""")

values = ",\n".join(rows)
sql = f"""-- Volume 1, Issue 1: full text of the 18 popular articles (source: "popular article-18 Re write.docx").
-- Generated by scripts/build-vol1-import-sql.py. Images are static files in public/articles/vol-1-issue-1/.
-- Six of these were already published as short versions; they are updated in place (same slug/URL).
-- Requires 20261002110000_article_authors.sql. Safe to re-run.

WITH data(slug, title, authors, abstract, content, cover_url, read_time, category_slug) AS (
VALUES
{values}
)
INSERT INTO public.articles
  (slug, title, authors, affiliation, abstract, content, cover_url, read_time, category_id, issue_id, status, published_at)
SELECT d.slug, d.title, d.authors, {q(AFFILIATION)}, d.abstract, d.content, d.cover_url, d.read_time,
       (SELECT id FROM public.categories c WHERE c.slug = d.category_slug),
       '{ISSUE_ID}', 'published', i.published_at
FROM data d
CROSS JOIN (SELECT published_at FROM public.issues WHERE id = '{ISSUE_ID}') i
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  authors = EXCLUDED.authors,
  affiliation = EXCLUDED.affiliation,
  abstract = EXCLUDED.abstract,
  content = EXCLUDED.content,
  cover_url = EXCLUDED.cover_url,
  read_time = EXCLUDED.read_time,
  category_id = EXCLUDED.category_id,
  issue_id = EXCLUDED.issue_id,
  status = 'published';

-- Homepage hero: drop the uploaded poster that has "Volume 6 · Issue 4 · June 2026" baked
-- into the image; the site falls back to the bundled field photos. Upload a new slide in
-- Admin → Content if you want a custom one.
DELETE FROM public.site_content WHERE page = 'home' AND section = 'hero' AND key = 'slide_images';
"""
open(sys.argv[2], "w").write(sql)
for a, (slug, title, cat) in zip(arts, META):
    print(f"{slug[:45]:45} | {authors(a['authors_raw'])}")
