/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SubmissionGuidelinesRouteImport } from './routes/submission-guidelines'
import { Route as StartupSpotlightRouteImport } from './routes/startup-spotlight'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ModerateRouteImport } from './routes/moderate'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as EditorialBoardRouteImport } from './routes/editorial-board'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurrentIssueRouteImport } from './routes/current-issue'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminIssuesRouteImport } from './routes/admin.issues'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionGuidelinesRoute = SubmissionGuidelinesRouteImport.update({
  id: '/submission-guidelines',
  path: '/submission-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupSpotlightRoute = StartupSpotlightRouteImport.update({
  id: '/startup-spotlight',
  path: '/startup-spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerateRoute = ModerateRouteImport.update({
  id: '/moderate',
  path: '/moderate',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialBoardRoute = EditorialBoardRouteImport.update({
  id: '/editorial-board',
  path: '/editorial-board',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentIssueRoute = CurrentIssueRouteImport.update({
  id: '/current-issue',
  path: '/current-issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssuesRoute = AdminIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/current-issue': typeof CurrentIssueRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/membership': typeof MembershipRoute
  '/moderate': typeof ModerateRoute
  '/search': typeof SearchRoute
  '/startup-spotlight': typeof StartupSpotlightRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/submit': typeof SubmitRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/current-issue': typeof CurrentIssueRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/membership': typeof MembershipRoute
  '/moderate': typeof ModerateRoute
  '/search': typeof SearchRoute
  '/startup-spotlight': typeof StartupSpotlightRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/submit': typeof SubmitRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archives': typeof ArchivesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/current-issue': typeof CurrentIssueRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-board': typeof EditorialBoardRoute
  '/membership': typeof MembershipRoute
  '/moderate': typeof ModerateRoute
  '/search': typeof SearchRoute
  '/startup-spotlight': typeof StartupSpotlightRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/submit': typeof SubmitRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/archives'
    | '/auth'
    | '/contact'
    | '/current-issue'
    | '/dashboard'
    | '/editorial-board'
    | '/membership'
    | '/moderate'
    | '/search'
    | '/startup-spotlight'
    | '/submission-guidelines'
    | '/submit'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/issues'
    | '/admin/queue'
    | '/admin/submissions'
    | '/articles/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archives'
    | '/auth'
    | '/contact'
    | '/current-issue'
    | '/dashboard'
    | '/editorial-board'
    | '/membership'
    | '/moderate'
    | '/search'
    | '/startup-spotlight'
    | '/submission-guidelines'
    | '/submit'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/issues'
    | '/admin/queue'
    | '/admin/submissions'
    | '/articles/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/archives'
    | '/auth'
    | '/contact'
    | '/current-issue'
    | '/dashboard'
    | '/editorial-board'
    | '/membership'
    | '/moderate'
    | '/search'
    | '/startup-spotlight'
    | '/submission-guidelines'
    | '/submit'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/issues'
    | '/admin/queue'
    | '/admin/submissions'
    | '/articles/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchivesRoute: typeof ArchivesRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CurrentIssueRoute: typeof CurrentIssueRoute
  DashboardRoute: typeof DashboardRoute
  EditorialBoardRoute: typeof EditorialBoardRoute
  MembershipRoute: typeof MembershipRoute
  ModerateRoute: typeof ModerateRoute
  SearchRoute: typeof SearchRoute
  StartupSpotlightRoute: typeof StartupSpotlightRoute
  SubmissionGuidelinesRoute: typeof SubmissionGuidelinesRoute
  SubmitRoute: typeof SubmitRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission-guidelines': {
      id: '/submission-guidelines'
      path: '/submission-guidelines'
      fullPath: '/submission-guidelines'
      preLoaderRoute: typeof SubmissionGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup-spotlight': {
      id: '/startup-spotlight'
      path: '/startup-spotlight'
      fullPath: '/startup-spotlight'
      preLoaderRoute: typeof StartupSpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderate': {
      id: '/moderate'
      path: '/moderate'
      fullPath: '/moderate'
      preLoaderRoute: typeof ModerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-board': {
      id: '/editorial-board'
      path: '/editorial-board'
      fullPath: '/editorial-board'
      preLoaderRoute: typeof EditorialBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-issue': {
      id: '/current-issue'
      path: '/current-issue'
      fullPath: '/current-issue'
      preLoaderRoute: typeof CurrentIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issues': {
      id: '/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AdminIssuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminIssuesRoute: typeof AdminIssuesRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminIssuesRoute: AdminIssuesRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchivesRoute: ArchivesRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CurrentIssueRoute: CurrentIssueRoute,
  DashboardRoute: DashboardRoute,
  EditorialBoardRoute: EditorialBoardRoute,
  MembershipRoute: MembershipRoute,
  ModerateRoute: ModerateRoute,
  SearchRoute: SearchRoute,
  StartupSpotlightRoute: StartupSpotlightRoute,
  SubmissionGuidelinesRoute: SubmissionGuidelinesRoute,
  SubmitRoute: SubmitRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
